### ISSUE TITLE
why not add support build to Dynamic Link Library for windows

### ISSUE THREAD

**Issue by loobins** [chronoxor/CppLogging#1]
It is a gread project， why not add support build to Dynamic Link Library for windows， 
same request for cppCommon。

**Comment by chronoxor** [comment]
If you need shared library it's easy to replace in CMakeLists.txt
```
add_library(cpplogging ${LIB_HEADER_FILES} ${LIB_INLINE_FILES} ${LIB_SOURCE_FILES} ${MINIZIP_FILES})
```
with
```
add_library(cpplogging SHARED ${LIB_HEADER_FILES} ${LIB_INLINE_FILES} ${LIB_SOURCE_FILES} ${MINIZIP_FILES})
```

In our projects we build everything from sources and all libs as static, than link into singe executable file. This gives us ability to debug everything we need and get rid of dll/so hell.
