### ISSUE TITLE
Generator platform not match

### ISSUE THREAD

**Issue by respec-kc** [chronoxor/CppLogging#6]
Running CMake for IfcOpenShell.

CMake Error: Error: generator platform: Win32
Does not match the platform used previously: ARM64
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.

An error occurred

How to deal with it? Thank you!

**Comment by chronoxor** [comment]
Please follow build instructions described in [CppLogging build guide](https://github.com/chronoxor/CppLogging#how-to-build)
